#!/usr/bin/env python3
"""Generate docs/data/airports.json — the dataset the destination search box
matches against. Hand-curated rather than pulled from a bulk source: a bulk
IATA list runs into the tens of thousands of disused airfields and codeshare
oddities, which would make the autocomplete noisy. This is deliberately a few
hundred airports a traveller would actually search for, weighted toward
Asia-Pacific since every search here departs from Singapore.
"""

import json
from pathlib import Path

# (code, city, country, airport name)
AIRPORTS = [
    # Southeast Asia
    ("SIN", "Singapore", "Singapore", "Changi"),
    ("KUL", "Kuala Lumpur", "Malaysia", "Kuala Lumpur International"),
    ("PEN", "Penang", "Malaysia", "Penang International"),
    ("LGK", "Langkawi", "Malaysia", "Langkawi International"),
    ("JHB", "Johor Bahru", "Malaysia", "Senai International"),
    ("KCH", "Kuching", "Malaysia", "Kuching International"),
    ("BKI", "Kota Kinabalu", "Malaysia", "Kota Kinabalu International"),
    ("BKK", "Bangkok", "Thailand", "Suvarnabhumi"),
    ("DMK", "Bangkok", "Thailand", "Don Mueang"),
    ("HKT", "Phuket", "Thailand", "Phuket International"),
    ("CNX", "Chiang Mai", "Thailand", "Chiang Mai International"),
    ("USM", "Koh Samui", "Thailand", "Samui"),
    ("KBV", "Krabi", "Thailand", "Krabi International"),
    ("CGK", "Jakarta", "Indonesia", "Soekarno-Hatta"),
    ("DPS", "Bali", "Indonesia", "Ngurah Rai (Denpasar)"),
    ("SUB", "Surabaya", "Indonesia", "Juanda International"),
    ("MDC", "Manado", "Indonesia", "Sam Ratulangi"),
    ("BPN", "Balikpapan", "Indonesia", "Sepinggan"),
    ("UPG", "Makassar", "Indonesia", "Sultan Hasanuddin"),
    ("SGN", "Ho Chi Minh City", "Vietnam", "Tan Son Nhat"),
    ("HAN", "Hanoi", "Vietnam", "Noi Bai"),
    ("DAD", "Da Nang", "Vietnam", "Da Nang International"),
    ("CXR", "Nha Trang", "Vietnam", "Cam Ranh"),
    ("PQC", "Phu Quoc", "Vietnam", "Phu Quoc International"),
    ("MNL", "Manila", "Philippines", "Ninoy Aquino"),
    ("CEB", "Cebu", "Philippines", "Mactan-Cebu"),
    ("DVO", "Davao", "Philippines", "Francisco Bangoy"),
    ("KLO", "Boracay", "Philippines", "Kalibo International"),
    ("PPS", "Puerto Princesa", "Philippines", "Puerto Princesa International"),
    ("PNH", "Phnom Penh", "Cambodia", "Phnom Penh International"),
    ("REP", "Siem Reap", "Cambodia", "Siem Reap"),
    ("VTE", "Vientiane", "Laos", "Wattay International"),
    ("LPQ", "Luang Prabang", "Laos", "Luang Prabang International"),
    ("RGN", "Yangon", "Myanmar", "Yangon International"),
    ("MDL", "Mandalay", "Myanmar", "Mandalay International"),
    ("BWN", "Bandar Seri Begawan", "Brunei", "Brunei International"),

    # East Asia
    ("PEK", "Beijing", "China", "Capital"),
    ("PKX", "Beijing", "China", "Daxing"),
    ("PVG", "Shanghai", "China", "Pudong"),
    ("SHA", "Shanghai", "China", "Hongqiao"),
    ("CAN", "Guangzhou", "China", "Baiyun"),
    ("SZX", "Shenzhen", "China", "Bao'an"),
    ("CTU", "Chengdu", "China", "Shuangliu"),
    ("HGH", "Hangzhou", "China", "Xiaoshan"),
    ("NKG", "Nanjing", "China", "Lukou"),
    ("XMN", "Xiamen", "China", "Gaoqi"),
    ("KMG", "Kunming", "China", "Changshui"),
    ("CKG", "Chongqing", "China", "Jiangbei"),
    ("WUH", "Wuhan", "China", "Tianhe"),
    ("XIY", "Xi'an", "China", "Xianyang"),
    ("TSN", "Tianjin", "China", "Binhai"),
    ("HRB", "Harbin", "China", "Taiping"),
    ("DLC", "Dalian", "China", "Zhoushuizi"),
    ("TAO", "Qingdao", "China", "Jiaodong"),
    ("SYX", "Sanya", "China", "Phoenix"),
    ("HAK", "Haikou", "China", "Meilan"),
    ("HKG", "Hong Kong", "Hong Kong", "Hong Kong International"),
    ("MFM", "Macau", "Macau", "Macau International"),
    ("TPE", "Taipei", "Taiwan", "Taoyuan"),
    ("TSA", "Taipei", "Taiwan", "Songshan"),
    ("KHH", "Kaohsiung", "Taiwan", "Kaohsiung International"),
    ("NRT", "Tokyo", "Japan", "Narita"),
    ("HND", "Tokyo", "Japan", "Haneda"),
    ("KIX", "Osaka", "Japan", "Kansai"),
    ("ITM", "Osaka", "Japan", "Itami"),
    ("NGO", "Nagoya", "Japan", "Chubu Centrair"),
    ("FUK", "Fukuoka", "Japan", "Fukuoka"),
    ("CTS", "Sapporo", "Japan", "New Chitose"),
    ("OKA", "Okinawa", "Japan", "Naha"),
    ("KOJ", "Kagoshima", "Japan", "Kagoshima"),
    ("SDJ", "Sendai", "Japan", "Sendai"),
    ("HIJ", "Hiroshima", "Japan", "Hiroshima"),
    ("ICN", "Seoul", "South Korea", "Incheon"),
    ("GMP", "Seoul", "South Korea", "Gimpo"),
    ("PUS", "Busan", "South Korea", "Gimhae"),
    ("CJU", "Jeju", "South Korea", "Jeju International"),

    # South Asia
    ("DEL", "Delhi", "India", "Indira Gandhi International"),
    ("BOM", "Mumbai", "India", "Chhatrapati Shivaji Maharaj"),
    ("BLR", "Bangalore", "India", "Kempegowda International"),
    ("MAA", "Chennai", "India", "Chennai International"),
    ("HYD", "Hyderabad", "India", "Rajiv Gandhi International"),
    ("CCU", "Kolkata", "India", "Netaji Subhas Chandra Bose"),
    ("COK", "Kochi", "India", "Cochin International"),
    ("GOI", "Goa", "India", "Dabolim"),
    ("AMD", "Ahmedabad", "India", "Sardar Vallabhbhai Patel"),
    ("PNQ", "Pune", "India", "Pune International"),
    ("CMB", "Colombo", "Sri Lanka", "Bandaranaike International"),
    ("MLE", "Male", "Maldives", "Velana International"),
    ("KTM", "Kathmandu", "Nepal", "Tribhuvan International"),
    ("DAC", "Dhaka", "Bangladesh", "Hazrat Shahjalal International"),
    ("KHI", "Karachi", "Pakistan", "Jinnah International"),
    ("LHE", "Lahore", "Pakistan", "Allama Iqbal International"),
    ("ISB", "Islamabad", "Pakistan", "Islamabad International"),

    # Oceania
    ("SYD", "Sydney", "Australia", "Kingsford Smith"),
    ("MEL", "Melbourne", "Australia", "Melbourne"),
    ("BNE", "Brisbane", "Australia", "Brisbane"),
    ("PER", "Perth", "Australia", "Perth"),
    ("ADL", "Adelaide", "Australia", "Adelaide"),
    ("OOL", "Gold Coast", "Australia", "Gold Coast"),
    ("CNS", "Cairns", "Australia", "Cairns"),
    ("DRW", "Darwin", "Australia", "Darwin"),
    ("HBA", "Hobart", "Australia", "Hobart"),
    ("AKL", "Auckland", "New Zealand", "Auckland"),
    ("WLG", "Wellington", "New Zealand", "Wellington"),
    ("CHC", "Christchurch", "New Zealand", "Christchurch"),
    ("ZQN", "Queenstown", "New Zealand", "Queenstown"),
    ("NAN", "Nadi", "Fiji", "Nadi International"),
    ("PPT", "Papeete", "French Polynesia", "Faa'a International"),
    ("GUM", "Guam", "Guam", "Antonio B. Won Pat"),
    ("ROR", "Koror", "Palau", "Roman Tmetuchl International"),

    # Middle East
    ("DXB", "Dubai", "UAE", "Dubai International"),
    ("AUH", "Abu Dhabi", "UAE", "Zayed International"),
    ("SHJ", "Sharjah", "UAE", "Sharjah International"),
    ("DOH", "Doha", "Qatar", "Hamad International"),
    ("JED", "Jeddah", "Saudi Arabia", "King Abdulaziz International"),
    ("RUH", "Riyadh", "Saudi Arabia", "King Khalid International"),
    ("DMM", "Dammam", "Saudi Arabia", "King Fahd International"),
    ("BAH", "Manama", "Bahrain", "Bahrain International"),
    ("KWI", "Kuwait City", "Kuwait", "Kuwait International"),
    ("MCT", "Muscat", "Oman", "Muscat International"),
    ("AMM", "Amman", "Jordan", "Queen Alia International"),
    ("TLV", "Tel Aviv", "Israel", "Ben Gurion"),
    ("IST", "Istanbul", "Turkey", "Istanbul Airport"),
    ("SAW", "Istanbul", "Turkey", "Sabiha Gokcen"),
    ("AYT", "Antalya", "Turkey", "Antalya"),
    ("ESB", "Ankara", "Turkey", "Esenboga"),

    # Europe
    ("LHR", "London", "United Kingdom", "Heathrow"),
    ("LGW", "London", "United Kingdom", "Gatwick"),
    ("LTN", "London", "United Kingdom", "Luton"),
    ("STN", "London", "United Kingdom", "Stansted"),
    ("MAN", "Manchester", "United Kingdom", "Manchester"),
    ("EDI", "Edinburgh", "United Kingdom", "Edinburgh"),
    ("BHX", "Birmingham", "United Kingdom", "Birmingham"),
    ("GLA", "Glasgow", "United Kingdom", "Glasgow"),
    ("CDG", "Paris", "France", "Charles de Gaulle"),
    ("ORY", "Paris", "France", "Orly"),
    ("NCE", "Nice", "France", "Cote d'Azur"),
    ("LYS", "Lyon", "France", "Saint-Exupery"),
    ("FRA", "Frankfurt", "Germany", "Frankfurt am Main"),
    ("MUC", "Munich", "Germany", "Franz Josef Strauss"),
    ("BER", "Berlin", "Germany", "Brandenburg"),
    ("DUS", "Dusseldorf", "Germany", "Dusseldorf"),
    ("HAM", "Hamburg", "Germany", "Hamburg"),
    ("AMS", "Amsterdam", "Netherlands", "Schiphol"),
    ("BRU", "Brussels", "Belgium", "Brussels"),
    ("ZRH", "Zurich", "Switzerland", "Zurich"),
    ("GVA", "Geneva", "Switzerland", "Geneva"),
    ("FCO", "Rome", "Italy", "Fiumicino"),
    ("MXP", "Milan", "Italy", "Malpensa"),
    ("VCE", "Venice", "Italy", "Marco Polo"),
    ("NAP", "Naples", "Italy", "Naples"),
    ("MAD", "Madrid", "Spain", "Barajas"),
    ("BCN", "Barcelona", "Spain", "El Prat"),
    ("AGP", "Malaga", "Spain", "Costa del Sol"),
    ("PMI", "Palma de Mallorca", "Spain", "Son Sant Joan"),
    ("LIS", "Lisbon", "Portugal", "Humberto Delgado"),
    ("OPO", "Porto", "Portugal", "Francisco Sa Carneiro"),
    ("VIE", "Vienna", "Austria", "Vienna International"),
    ("DUB", "Dublin", "Ireland", "Dublin"),
    ("CPH", "Copenhagen", "Denmark", "Kastrup"),
    ("ARN", "Stockholm", "Sweden", "Arlanda"),
    ("OSL", "Oslo", "Norway", "Gardermoen"),
    ("HEL", "Helsinki", "Finland", "Helsinki-Vantaa"),
    ("WAW", "Warsaw", "Poland", "Chopin"),
    ("PRG", "Prague", "Czech Republic", "Vaclav Havel"),
    ("BUD", "Budapest", "Hungary", "Ferenc Liszt"),
    ("ATH", "Athens", "Greece", "Eleftherios Venizelos"),
    ("SVO", "Moscow", "Russia", "Sheremetyevo"),
    ("DME", "Moscow", "Russia", "Domodedovo"),
    ("LED", "St Petersburg", "Russia", "Pulkovo"),
    ("KEF", "Reykjavik", "Iceland", "Keflavik"),

    # North America
    ("JFK", "New York", "United States", "John F. Kennedy"),
    ("EWR", "Newark", "United States", "Newark Liberty"),
    ("LGA", "New York", "United States", "LaGuardia"),
    ("LAX", "Los Angeles", "United States", "Los Angeles International"),
    ("SFO", "San Francisco", "United States", "San Francisco International"),
    ("ORD", "Chicago", "United States", "O'Hare"),
    ("DFW", "Dallas", "United States", "Dallas/Fort Worth"),
    ("ATL", "Atlanta", "United States", "Hartsfield-Jackson"),
    ("MIA", "Miami", "United States", "Miami International"),
    ("SEA", "Seattle", "United States", "Seattle-Tacoma"),
    ("BOS", "Boston", "United States", "Logan International"),
    ("IAD", "Washington", "United States", "Dulles"),
    ("DCA", "Washington", "United States", "Reagan National"),
    ("DEN", "Denver", "United States", "Denver International"),
    ("LAS", "Las Vegas", "United States", "Harry Reid"),
    ("PHX", "Phoenix", "United States", "Sky Harbor"),
    ("IAH", "Houston", "United States", "George Bush"),
    ("MSP", "Minneapolis", "United States", "Minneapolis-St Paul"),
    ("DTW", "Detroit", "United States", "Detroit Metro"),
    ("PHL", "Philadelphia", "United States", "Philadelphia International"),
    ("SAN", "San Diego", "United States", "San Diego International"),
    ("HNL", "Honolulu", "United States", "Daniel K. Inouye"),
    ("PDX", "Portland", "United States", "Portland International"),
    ("YYZ", "Toronto", "Canada", "Pearson"),
    ("YVR", "Vancouver", "Canada", "Vancouver International"),
    ("YUL", "Montreal", "Canada", "Trudeau"),
    ("YYC", "Calgary", "Canada", "Calgary International"),
    ("YOW", "Ottawa", "Canada", "Macdonald-Cartier"),
    ("MEX", "Mexico City", "Mexico", "Benito Juarez"),
    ("CUN", "Cancun", "Mexico", "Cancun International"),
    ("GDL", "Guadalajara", "Mexico", "Miguel Hidalgo"),

    # South America
    ("GRU", "Sao Paulo", "Brazil", "Guarulhos"),
    ("GIG", "Rio de Janeiro", "Brazil", "Galeao"),
    ("BSB", "Brasilia", "Brazil", "Brasilia International"),
    ("EZE", "Buenos Aires", "Argentina", "Ezeiza"),
    ("SCL", "Santiago", "Chile", "Arturo Merino Benitez"),
    ("LIM", "Lima", "Peru", "Jorge Chavez"),
    ("BOG", "Bogota", "Colombia", "El Dorado"),

    # Africa
    ("JNB", "Johannesburg", "South Africa", "O.R. Tambo"),
    ("CPT", "Cape Town", "South Africa", "Cape Town International"),
    ("DUR", "Durban", "South Africa", "King Shaka"),
    ("NBO", "Nairobi", "Kenya", "Jomo Kenyatta"),
    ("CAI", "Cairo", "Egypt", "Cairo International"),
    ("CMN", "Casablanca", "Morocco", "Mohammed V"),
    ("ADD", "Addis Ababa", "Ethiopia", "Bole International"),
    ("JRO", "Kilimanjaro", "Tanzania", "Kilimanjaro International"),
    ("DAR", "Dar es Salaam", "Tanzania", "Julius Nyerere"),
    ("MRU", "Mauritius", "Mauritius", "Sir Seewoosagur Ramgoolam"),
    ("SEZ", "Seychelles", "Seychelles", "Seychelles International"),
]


def main():
    seen = set()
    records = []
    for code, city, country, name in AIRPORTS:
        if code in seen:
            raise SystemExit(f"duplicate code: {code}")
        seen.add(code)
        records.append({"code": code, "city": city, "country": country, "name": name})

    records.sort(key=lambda r: (r["country"], r["city"]))
    out = Path(__file__).resolve().parent.parent / "docs" / "data" / "airports.json"
    out.write_text(json.dumps(records, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    print(f"wrote {len(records)} airports to {out}")


if __name__ == "__main__":
    main()
